name: "Docker Publish with tags"
on:
  push:
    tags: 
        - "v*"
  workflow_dispatch:
jobs:
 
  build-and-push-image-with-tags:
    runs-on: ubuntu-latest

    steps:
    - name: "Checkout"
      uses: "actions/checkout@v4"
      
    - name: "Login to Docker hub"
      uses: docker/login-action@v3
      with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: "Set up QEMU"
      uses: "docker/setup-qemu-action@v3"
    - name: "Set up Docker Buildx"
      uses: "docker/setup-buildx-action@v3"
          
    - name: "Build and push image tags"
      uses: "docker/build-push-action@v6"
      with:
         push: true
         tags: |
           "${{ github.repository }}:latest"
           "${{ github.repository }}:${{ github.ref_name }}"
      
    
